name: Deploy Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, welearn-be]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Go to _work directory
        run: cd /home/ec2-user/welearn/runners/backend/_work/WeLearn-Backend/WeLearn-Backend
      - name: Deploy code
        run: |
          rsync -av --delete ./ /home/ec2-user/welearn/app/WeLearn-Backend/ --exclude .env
      - name: Install dependencies
        run: |
          cd /home/ec2-user/welearn/app/WeLearn-Backend
          npm install
      - name: Restart PM2 process
        run: |
          cd /home/ec2-user/welearn/app/WeLearn-Backend
          pm2 restart backend